version: '3'

services:
  frontend:
    # use pre-built image for shortcut
    #build: ./frontend
    image: ghcr.io/tyage/camp.app1-frontend:main
    ports:
      - 30080:3000
    environment:
      - NEXT_PUBLIC_AUTH_API_BASE=http://localhost:30082
      - NEXT_PUBLIC_NOTIFICATION_API_BASE=http://localhost:30081

  notification:
    build: ./notification
    ports:
      - 30081:8080
    environment:
      - JWT_SECRET=superdupersecretkey

  auth:
    # use pre-built image for shortcut
    #build: ./auth
    image: ghcr.io/tyage/camp.app1-auth:main
    ports:
      - 30082:3000
    environment:
      - NOTIFICATION_JWT_SECRET=superdupersecretkey
