version: '3'

services:
  resource:
    build: ./resource-server
    ports:
      - 30081:8080
  auth:
    build: ./auth-server
    ports:
      - 30082:3000
  frontend:
    image: nginx
    volumes:
      - ./frontend-server/html:/usr/share/nginx/html
    ports:
      - 30080:80
