version: '3'

services:
  notification:
    build: ./notification-server
    ports:
      - 30081:8080
    environment:
      - JWT_SECRET=superdupersecretkey

  auth:
    build: ./auth-server
    ports:
      - 30082:3000
    environment:
      - NOTIFICATION_JWT_SECRET=superdupersecretkey

  frontend:
    image: nginx
    volumes:
      - ./frontend-server/html:/usr/share/nginx/html
    ports:
      - 30080:80
    environment:
      - NEXT_PUBLIC_AUTH_API_BASE=http://localhost:30082
      - NEXT_PUBLIC_NOTIFICATION_API_BASE=http://localhost:30081
